// @front-native__old/components/games/GameSessions.tsx
import { View, Text, ScrollView, ActivityIndicator } from 'react-native';
import { useState, useEffect } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { useFamilyStore } from '@/stores/familyStore';

interface PlayerScore {
  id: number;
  score: number;
  is_winner?: boolean;
  position?: number;
  member: {
    id: number;
    username: string;
  };
}

interface GameSession {
  id: number;
  played_at: string;
  notes?: string;
  player_scores?: PlayerScore[];
}

interface GameSessionsProps {
  gameId: number;
}

const AVATAR_COLORS = [
  { bg: 'bg-blue-100', text: 'text-blue-600' },
  { bg: 'bg-cyan-100', text: 'text-cyan-600' },
  { bg: 'bg-green-100', text: 'text-green-600' },
  { bg: 'bg-amber-100', text: 'text-amber-600' },
  { bg: 'bg-red-100', text: 'text-red-600' },
  { bg: 'bg-purple-100', text: 'text-purple-600' },
  { bg: 'bg-pink-100', text: 'text-pink-600' },
  { bg: 'bg-indigo-100', text: 'text-indigo-600' },
];

const getMemberAvatarColor = (memberId: number) => {
  return AVATAR_COLORS[memberId % AVATAR_COLORS.length];
};

const sortedScores = (scores: PlayerScore[]) => {
  return [...scores].sort((a, b) => {
    if (a.is_winner && !b.is_winner) return -1;
    if (!a.is_winner && b.is_winner) return 1;
    return b.score - a.score;
  });
};

const formatDate = (dateString: string) => {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat('fr-FR', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
};

export function GameSessions({ gameId }: GameSessionsProps) {
  const [sessions, setSessions] = useState<GameSession[]>([]);
  const [loading, setLoading] = useState(true);
  const familyStore = useFamilyStore();

  useEffect(() => {
    loadSessions();
  }, [gameId]);

  const loadSessions = async () => {
    setLoading(true);
    try {
      const result = await familyStore.fetchGameSessions(gameId);
      if (result.success && result.data) {
        setSessions(result.data);
      }
    } catch (error) {
      console.error('Erreur lors du chargement des parties:', error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <View className="flex-1 items-center justify-center py-8">
        <ActivityIndicator size="large" color="#3B82F6" />
      </View>
    );
  }

  if (sessions.length === 0) {
    return (
      <View className="flex-1 items-center justify-center py-12">
        <Ionicons name="game-controller-outline" size={64} color="#9CA3AF" />
        <Text className="text-gray-500 mt-4">Aucune partie enregistrée pour ce jeu</Text>
      </View>
    );
  }

  return (
    <View className="flex-1">
      <ScrollView className="flex-1">
        <View className="space-y-4">
          {sessions.map((session) => {
            const scores = session.player_scores || [];
            const sortedPlayerScores = sortedScores(scores);

            return (
              <View key={session.id} className="bg-white p-4 rounded-lg mb-4">
                {/* Header */}
                <View className="flex-row items-center justify-between mb-3">
                  <View className="flex-row items-center gap-2">
                    <Ionicons name="calendar-outline" size={16} color="#6B7280" />
                    <Text className="font-semibold text-gray-900">
                      {formatDate(session.played_at)}
                    </Text>
                  </View>
                  {session.notes && (
                    <View className="bg-gray-100 px-2 py-1 rounded-md flex-row items-center gap-1">
                      <Ionicons name="document-text-outline" size={12} color="#6B7280" />
                      <Text className="text-xs text-gray-600">Notes</Text>
                    </View>
                  )}
                </View>

                {/* Notes */}
                {session.notes && (
                  <View className="mb-3">
                    <Text className="text-sm text-gray-600 italic">{session.notes}</Text>
                  </View>
                )}

                {/* Scores */}
                <View className="space-y-2">
                  {sortedPlayerScores.map((score, index) => {
                    const avatarColor = getMemberAvatarColor(score.member.id);
                    const isWinner = score.is_winner;

                    return (
                      <View
                        key={score.id}
                        className={`flex-row items-center justify-between p-2 rounded ${
                          isWinner ? 'bg-blue-50' : ''
                        }`}
                      >
                        <View className="flex-row items-center gap-3">
                          {/* Position ou Crown */}
                          <View className="w-4 items-center justify-center">
                            {isWinner ? (
                              <Ionicons name="trophy" size={16} color="#EAB308" />
                            ) : (
                              <Text className="text-xs text-gray-400">
                                {score.position || index + 1}
                              </Text>
                            )}
                          </View>

                          {/* Avatar */}
                          <View
                            className={`w-8 h-8 rounded-full items-center justify-center ${avatarColor.bg}`}
                          >
                            <Text className={`text-xs font-semibold ${avatarColor.text}`}>
                              {score.member.username.charAt(0).toUpperCase()}
                            </Text>
                          </View>

                          {/* Nom */}
                          <Text className="font-medium text-gray-900">
                            {score.member.username}
                          </Text>
                        </View>

                        {/* Score */}
                        <Text className="font-bold text-gray-900">{score.score}</Text>
                      </View>
                    );
                  })}
                </View>
              </View>
            );
          })}
        </View>
      </ScrollView>
    </View>
  );
}

// @front/app/components/GameSessions.vue
<template>
  <div class="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
    <div class="flex items-center justify-between mb-4">
      <h2 class="text-xl font-bold flex items-center gap-2">
        <UIcon
          name="i-lucide-trophy"
          class="w-5 h-5"
        />
        Parties jouées
      </h2>
      <UButton
        color="primary"
        size="sm"
        icon="i-lucide-plus"
        @click="openAddSessionModal"
      >
        Ajouter une partie
      </UButton>
    </div>

    <div
      v-if="loading"
      class="flex justify-center items-center py-8"
    >
      <UIcon
        name="i-lucide-loader-2"
        class="w-6 h-6 animate-spin text-primary-500"
      />
    </div>

    <div
      v-else-if="sessions.length === 0"
      class="text-center py-8 text-gray-500 dark:text-gray-400"
    >
      <UIcon
        name="i-lucide-gamepad-2"
        class="w-12 h-12 mx-auto mb-3 opacity-50"
      />
      <p>Aucune partie enregistrée pour ce jeu</p>
    </div>

    <div
      v-else
      class="space-y-4"
    >
      <div
        v-for="session in sessions"
        :key="session.id"
        class="p-4 bg-gray-50 dark:bg-gray-800 rounded-lg"
      >
        <div class="flex items-center justify-between mb-3">
          <div class="flex items-center gap-2">
            <UIcon
              name="i-lucide-calendar"
              class="w-4 h-4 text-gray-500"
            />
            <span class="font-semibold">
              {{ formatDate(session.played_at) }}
            </span>
          </div>
          <UBadge
            v-if="session.notes"
            color="gray"
            variant="subtle"
            icon="i-lucide-file-text"
          >
            Notes
          </UBadge>
        </div>

        <div
          v-if="session.notes"
          class="mb-3 text-sm text-gray-600 dark:text-gray-400 italic"
        >
          {{ session.notes }}
        </div>

        <div class="space-y-2">
          <div
            v-for="score in sortedScores(session.player_scores || [])"
            :key="score.id"
            class="flex items-center justify-between p-2 rounded"
            :class="score.is_winner ? 'bg-primary-50 dark:bg-primary-900/20' : ''"
          >
            <div class="flex items-center gap-3">
              <div
                v-if="score.is_winner"
                class="flex items-center gap-1"
              >
                <UIcon
                  name="i-lucide-crown"
                  class="w-4 h-4 text-yellow-500"
                />
              </div>
              <div
                v-else
                class="w-4 h-4 flex items-center justify-center"
              >
                <span class="text-xs text-gray-400">
                  {{ score.position }}
                </span>
              </div>
              <div class="w-8 h-8 rounded-full bg-primary-100 dark:bg-primary-900 flex items-center justify-center">
                <span class="text-xs font-semibold text-primary-600 dark:text-primary-400">
                  {{ score.member.username.charAt(0).toUpperCase() }}
                </span>
              </div>
              <span class="font-medium">{{ score.member.username }}</span>
            </div>
            <div class="flex items-center gap-2">
              <span class="font-bold">{{ score.score }}</span>
              <span
                v-if="score.is_winner"
                class="text-xs text-yellow-600 dark:text-yellow-400 font-semibold"
              >
                Gagnant
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <UModal
      :open="isAddModalOpen"
      :fullscreen="isMobile"
      @update:open="(value) => { isAddModalOpen = value }"
    >
      <template #content>
        <UCard class="w-full md:max-w-2xl md:max-h-[90vh] flex flex-col">
          <template #header>
            <div class="flex items-center justify-between">
              <h3 class="text-lg font-semibold">
                Ajouter une partie
              </h3>
              <div class="flex items-center gap-2">
                <UButton
                  type="submit"
                  form="session-form"
                  color="primary"
                  size="sm"
                  :loading="isSubmitting"
                >
                  Enregistrer
                </UButton>
                <UButton
                  color="neutral"
                  variant="ghost"
                  icon="i-lucide-x"
                  size="sm"
                  class="-my-1"
                  :disabled="isSubmitting"
                  @click="closeModal"
                />
              </div>
            </div>
          </template>

          <form
            id="session-form"
            class="space-y-4 overflow-y-auto flex-1"
            @submit.prevent="handleAddSession"
          >
            <div>
              <label
                for="played_at"
                class="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
              >
                <UIcon
                  name="i-lucide-calendar"
                  class="w-4 h-4"
                />
                Date et heure de la partie <span class="text-red-500">*</span>
              </label>
              <UInput
                id="played_at"
                v-model="newSession.played_at"
                type="datetime-local"
                :disabled="isSubmitting"
                :error="!!errors.played_at"
                class="w-full"
                required
              />
              <p
                v-if="errors.played_at"
                class="mt-1 text-sm text-red-600 dark:text-red-400"
              >
                {{ errors.played_at }}
              </p>
            </div>

            <div>
              <label
                for="notes"
                class="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
              >
                <UIcon
                  name="i-lucide-file-text"
                  class="w-4 h-4"
                />
                Notes (optionnel)
              </label>
              <UTextarea
                id="notes"
                v-model="newSession.notes"
                placeholder="Ajouter des notes sur cette partie..."
                rows="3"
                :disabled="isSubmitting"
                class="w-full"
              />
            </div>

            <div>
              <label class="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
                <UIcon
                  name="i-lucide-users"
                  class="w-4 h-4"
                />
                Scores des joueurs <span class="text-red-500">*</span>
              </label>
              <div class="space-y-3">
                <div
                  v-for="member in familyMembers"
                  :key="member.id"
                  class="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg"
                >
                  <div class="w-8 h-8 rounded-full bg-primary-100 dark:bg-primary-900 flex items-center justify-center flex-shrink-0">
                    <span class="text-xs font-semibold text-primary-600 dark:text-primary-400">
                      {{ member.username.charAt(0).toUpperCase() }}
                    </span>
                  </div>
                  <span class="flex-1 font-medium">{{ member.username }}</span>
                  <UInput
                    v-model.number="newSession.scores[member.id]"
                    type="number"
                    placeholder="Score"
                    class="w-24"
                    :min="0"
                    step="0.01"
                    :disabled="isSubmitting"
                  />
                </div>
              </div>
              <p
                v-if="errors.scores"
                class="mt-1 text-sm text-red-600 dark:text-red-400"
              >
                {{ errors.scores }}
              </p>
            </div>

            <div
              v-if="submitError"
              class="p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg"
            >
              <p class="text-sm text-red-600 dark:text-red-400">
                {{ submitError }}
              </p>
            </div>
          </form>
        </UCard>
      </template>
    </UModal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, reactive, watch } from 'vue'
import { useMediaQuery } from '@vueuse/core'
import { useFamilyStore, type GameSession, type PlayerScore } from '~/stores/family'

const isMobile = useMediaQuery('(max-width: 767px)')

const props = defineProps<{
  gameId: number
}>()

const familyStore = useFamilyStore()
const sessions = ref<GameSession[]>([])
const loading = ref(false)
const isAddModalOpen = ref(false)
const isSubmitting = ref(false)
const submitError = ref<string | null>(null)

const newSession = ref({
  played_at: new Date().toISOString().slice(0, 16),
  notes: '',
  scores: {} as Record<number, number>
})

const errors = reactive({
  played_at: '',
  scores: ''
})

const familyMembers = computed(() => familyStore.familyMembers)

watch(() => newSession.value.played_at, () => {
  if (errors.played_at) errors.played_at = ''
})

watch(() => newSession.value.scores, () => {
  if (errors.scores) errors.scores = ''
}, { deep: true })

const sortedScores = (scores: PlayerScore[]) => {
  return [...scores].sort((a, b) => {
    if (a.is_winner && !b.is_winner) return -1
    if (!a.is_winner && b.is_winner) return 1
    return (b.score - a.score)
  })
}

const formatDate = (dateString: string) => {
  const date = new Date(dateString)
  return new Intl.DateTimeFormat('fr-FR', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  }).format(date)
}

const resetForm = () => {
  newSession.value = {
    played_at: new Date().toISOString().slice(0, 16),
    notes: '',
    scores: {} as Record<number, number>
  }
  submitError.value = null
  errors.played_at = ''
  errors.scores = ''
}

const openAddSessionModal = () => {
  resetForm()
  isAddModalOpen.value = true
}

const validateForm = (): boolean => {
  let isValid = true
  errors.played_at = ''
  errors.scores = ''

  if (!newSession.value.played_at) {
    errors.played_at = 'La date et l\'heure sont requises'
    isValid = false
  }

  const scores = Object.entries(newSession.value.scores)
    .filter(([_, score]) => score !== undefined && score !== null && score !== '')

  if (scores.length === 0) {
    errors.scores = 'Au moins un score est requis'
    isValid = false
  }

  return isValid
}

const closeModal = () => {
  if (!isSubmitting.value) {
    resetForm()
    isAddModalOpen.value = false
  }
}

const handleAddSession = async () => {
  if (!validateForm()) {
    return
  }

  const scores = Object.entries(newSession.value.scores)
    .filter(([_, score]) => score !== undefined && score !== null && score !== '')
    .map(([memberId, score]) => ({
      memberId: parseInt(memberId, 10),
      score: Number(score)
    }))

  isSubmitting.value = true
  submitError.value = null

  try {
    const playedAt = new Date(newSession.value.played_at).toISOString()
    const result = await familyStore.createGameSession(
      props.gameId,
      playedAt,
      scores,
      newSession.value.notes || undefined
    )

    if (result.success) {
      resetForm()
      isAddModalOpen.value = false
      await loadSessions()
    } else {
      submitError.value = result.error || 'Erreur lors de l\'enregistrement de la partie'
    }
  } catch (error) {
    console.error('Erreur lors de l\'ajout de la partie:', error)
    submitError.value = 'Une erreur est survenue lors de l\'enregistrement de la partie'
  } finally {
    isSubmitting.value = false
  }
}

const loadSessions = async () => {
  loading.value = true
  try {
    const result = await familyStore.fetchGameSessions(props.gameId)
    if (result.success && result.data) {
      sessions.value = result.data
    }
  } catch (error) {
    console.error('Erreur lors du chargement des parties:', error)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadSessions()
})
</script>
