// @front-native__old/app/games/[id].tsx
import { View, Text, ScrollView, Image, TouchableOpacity, ActivityIndicator, Alert } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useState, useEffect } from 'react';
import { useFamilyStore } from '@/stores/familyStore';
import AppHeader from '@/components/AppHeader';
import { InteractiveStarRating } from '@/components/games/InteractiveStarRating';
import { Badge } from '@/components/games/Badge';
import { GameSessions } from '@/components/games/GameSessions';
import { Ionicons } from '@expo/vector-icons';

interface Rating {
  id: number;
  rating: number;
  member: {
    id: number;
  };
}

interface WinnerData {
  member: {
    id: number;
    username: string;
  };
  wins: number;
}

const AVATAR_COLORS = [
  { bg: 'bg-blue-100', text: 'text-blue-600' },
  { bg: 'bg-green-100', text: 'text-green-600' },
  { bg: 'bg-purple-100', text: 'text-purple-600' },
  { bg: 'bg-pink-100', text: 'text-pink-600' },
  { bg: 'bg-orange-100', text: 'text-orange-600' },
  { bg: 'bg-indigo-100', text: 'text-indigo-600' },
  { bg: 'bg-red-100', text: 'text-red-600' },
  { bg: 'bg-yellow-100', text: 'text-yellow-600' },
];

const getMemberAvatarColor = (memberId: number) => {
  return AVATAR_COLORS[memberId % AVATAR_COLORS.length];
};

export default function GameDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const gameId = parseInt(id || '0', 10);

  const [activeTab, setActiveTab] = useState<'detail' | 'notes' | 'parties' | 'podium'>('detail');
  const [loading, setLoading] = useState(true);
  const [top3Winners, setTop3Winners] = useState<WinnerData[]>([]);

  const familyStore = useFamilyStore();
  const games = familyStore.getTransformedGames();
  const members = familyStore.getFamilyMembers();
  const game = games.find((g) => g.id === gameId);

  useEffect(() => {
    loadData();
  }, [gameId]);

  const loadData = async () => {
    setLoading(true);
    await familyStore.fetchFamily();
    await loadTop3Winners();
    setLoading(false);
  };

  const loadTop3Winners = async () => {
    const result = await familyStore.getTop3Winners(gameId);
    if (result.success && result.data) {
      setTop3Winners(result.data);
    }
  };

  const getMemberRating = (memberId: number): number => {
    if (!game?.ratings) return 0;
    const memberRating = game.ratings.find((r: Rating) => r.member.id === memberId);
    return memberRating ? memberRating.rating : 0;
  };

  const setMemberRating = async (memberId: number, rating: number) => {
    const result = await familyStore.setRating(gameId, memberId, rating);
    if (!result.success) {
      Alert.alert('Erreur', result.error || 'Erreur lors de l\'enregistrement de la note');
    }
  };

  const deleteMemberRating = async (memberId: number) => {
    Alert.alert(
      'Supprimer la note',
      'Voulez-vous vraiment supprimer cette note ?',
      [
        { text: 'Annuler', style: 'cancel' },
        {
          text: 'Supprimer',
          style: 'destructive',
          onPress: () => setMemberRating(memberId, 0),
        },
      ]
    );
  };

  const calculateAverageRating = (): number => {
    if (!game?.ratings || game.ratings.length === 0) return 0;
    const ratings = game.ratings.filter((r: Rating) => r.rating > 0);
    if (ratings.length === 0) return 0;
    const sum = ratings.reduce((acc: number, r: Rating) => acc + r.rating, 0);
    return sum / ratings.length;
  };

  if (loading) {
    return (
      <View className="flex-1 bg-gray-100">
        <AppHeader title="Détail du jeu" showBackButton={true} />
        <View className="flex-1 justify-center items-center">
          <ActivityIndicator size="large" color="#3B82F6" />
        </View>
      </View>
    );
  }

  if (!game) {
    return (
      <View className="flex-1 bg-gray-100">
        <AppHeader title="Détail du jeu" showBackButton={true} />
        <View className="flex-1 justify-center items-center p-5">
          <Ionicons name="alert-circle-outline" size={64} color="#9CA3AF" />
          <Text className="text-xl font-bold text-gray-700 mt-4">Jeu non trouvé</Text>
          <Text className="text-gray-500 mt-2 text-center">
            Le jeu que vous recherchez n'existe pas ou n'est plus disponible.
          </Text>
        </View>
      </View>
    );
  }

  const averageRating = calculateAverageRating();

  return (
    <View className="flex-1 bg-gray-100">
      <AppHeader title={game.titre} showBackButton={true} />

      {/* Tabs */}
      <View className="bg-white border-b border-gray-200">
        <View className="flex-row">
          <TouchableOpacity
            onPress={() => setActiveTab('detail')}
            className={`flex-1 flex-row items-center justify-center py-3 border-b-2 ${
              activeTab === 'detail' ? 'border-blue-500' : 'border-transparent'
            }`}
          >
            <Ionicons
              name="information-circle"
              size={20}
              color={activeTab === 'detail' ? '#3B82F6' : '#9CA3AF'}
            />
            <Text
              className={`ml-2 font-medium ${
                activeTab === 'detail' ? 'text-blue-500' : 'text-gray-500'
              }`}
            >
              Détail
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            onPress={() => setActiveTab('notes')}
            className={`flex-1 flex-row items-center justify-center py-3 border-b-2 ${
              activeTab === 'notes' ? 'border-blue-500' : 'border-transparent'
            }`}
          >
            <Ionicons
              name="star"
              size={20}
              color={activeTab === 'notes' ? '#3B82F6' : '#9CA3AF'}
            />
            <Text
              className={`ml-2 font-medium ${
                activeTab === 'notes' ? 'text-blue-500' : 'text-gray-500'
              }`}
            >
              Notes
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            onPress={() => setActiveTab('parties')}
            className={`flex-1 flex-row items-center justify-center py-3 border-b-2 ${
              activeTab === 'parties' ? 'border-blue-500' : 'border-transparent'
            }`}
          >
            <Ionicons
              name="game-controller"
              size={20}
              color={activeTab === 'parties' ? '#3B82F6' : '#9CA3AF'}
            />
            <Text
              className={`ml-2 font-medium ${
                activeTab === 'parties' ? 'text-blue-500' : 'text-gray-500'
              }`}
            >
              Parties
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            onPress={() => setActiveTab('podium')}
            className={`flex-row items-center justify-center px-4 py-3 border-b-2 ${
              activeTab === 'podium' ? 'border-blue-500' : 'border-transparent'
            }`}
          >
            <Ionicons
              name="trophy"
              size={20}
              color={activeTab === 'podium' ? '#3B82F6' : '#9CA3AF'}
            />
          </TouchableOpacity>
        </View>
      </View>

      {/* Tab Content */}
      <ScrollView className="flex-1">
        {/* Onglet Détail */}
        {activeTab === 'detail' && (
          <View className="p-5 space-y-4">
            {/* Image */}
            <View className="w-full h-48 rounded-lg bg-gray-200 overflow-hidden">
              {game.image ? (
                <Image
                  source={{ uri: game.image }}
                  className="w-full h-full"
                  resizeMode="contain"
                />
              ) : (
                <View className="flex-1 items-center justify-center">
                  <Ionicons name="image-outline" size={48} color="#9CA3AF" />
                  <Text className="text-gray-400 text-xs mt-2">Aucune image</Text>
                </View>
              )}
            </View>

            {/* Note moyenne */}
            {averageRating > 0 && (
              <View className="bg-blue-50 p-3 rounded-lg">
                <InteractiveStarRating
                  rating={averageRating}
                  size={24}
                  readonly
                />
              </View>
            )}

            {/* Badges */}
            <View className="flex-row flex-wrap gap-2">
              <Badge variant="neutral">
                {game.age_min}
                {game.age_max ? `-${game.age_max}` : '+'}
                {' ans'}
              </Badge>
              {game.tags.map((tag, index) => (
                <Badge key={index} variant={tag.includes('joueurs') ? 'info' : 'primary'}>
                  {tag}
                </Badge>
              ))}
            </View>

            {/* Description */}
            {game.description && (
              <View className="bg-white p-4 rounded-lg">
                <Text className="text-gray-700">{game.description}</Text>
              </View>
            )}
          </View>
        )}

        {/* Onglet Notes */}
        {activeTab === 'notes' && (
          <View className="p-5 space-y-4">
            {members.length > 0 ? (
              <>
                {members.map((member) => {
                  const memberRating = getMemberRating(member.id);
                  const avatarColor = getMemberAvatarColor(member.id);

                  return (
                    <View key={member.id} className="bg-white p-4 rounded-lg">
                      <View className="flex-row items-center justify-between mb-3">
                        <View className="flex-row items-center flex-1">
                          <View
                            className={`w-10 h-10 rounded-full items-center justify-center ${avatarColor.bg}`}
                          >
                            <Text className={`text-sm font-semibold ${avatarColor.text}`}>
                              {member.username.charAt(0).toUpperCase()}
                            </Text>
                          </View>
                          <Text className="ml-3 font-medium text-gray-700">
                            {member.username}
                          </Text>
                        </View>
                        {memberRating > 0 && (
                          <TouchableOpacity
                            onPress={() => deleteMemberRating(member.id)}
                            className="p-2"
                          >
                            <Ionicons name="trash-outline" size={20} color="#EF4444" />
                          </TouchableOpacity>
                        )}
                      </View>
                      <InteractiveStarRating
                        rating={memberRating}
                        onRatingChange={(rating) => setMemberRating(member.id, rating)}
                      />
                    </View>
                  );
                })}

                {/* Note moyenne */}
                {averageRating > 0 && (
                  <View className="bg-white p-4 rounded-lg">
                    <View className="flex-row items-center justify-between">
                      <Text className="font-semibold text-blue-900">Note moyenne</Text>
                      <View className="flex-row items-center">
                        <InteractiveStarRating rating={averageRating} size={20} readonly />
                        <Text className="text-lg font-bold text-blue-600 ml-2">
                          {averageRating.toFixed(1)} / 5
                        </Text>
                      </View>
                    </View>
                  </View>
                )}
              </>
            ) : (
              <View className="flex-1 items-center justify-center py-12">
                <Ionicons name="people-outline" size={64} color="#9CA3AF" />
                <Text className="text-gray-500 mt-4">Aucun membre dans la famille</Text>
              </View>
            )}
          </View>
        )}

        {/* Onglet Parties */}
        {activeTab === 'parties' && (
          <View className="p-5">
            <GameSessions gameId={gameId} />
          </View>
        )}

        {/* Onglet Podium */}
        {activeTab === 'podium' && (
          <View className="p-5">
            {top3Winners.length > 0 ? (
              <View className="bg-white rounded-lg p-4">
                {/* Podium */}
                <View className="flex-row items-end justify-center mb-6" style={{ height: 200 }}>
                  {/* 2ème place */}
                  {top3Winners[1] && (
                    <View className="flex-1 items-center mx-1">
                      <Text className="text-3xl mb-2">🥈</Text>
                      <View
                        className={`w-14 h-14 rounded-full items-center justify-center mb-2 ${
                          getMemberAvatarColor(top3Winners[1].member.id).bg
                        }`}
                      >
                        <Text
                          className={`text-lg font-bold ${
                            getMemberAvatarColor(top3Winners[1].member.id).text
                          }`}
                        >
                          {top3Winners[1].member.username.charAt(0).toUpperCase()}
                        </Text>
                      </View>
                      <View className="bg-gray-300 w-full rounded-t-lg p-2" style={{ height: 90 }}>
                        <Text className="text-xs font-bold text-gray-800 text-center">2ème</Text>
                        <Text
                          className="text-sm font-bold text-gray-900 text-center"
                          numberOfLines={1}
                        >
                          {top3Winners[1].member.username}
                        </Text>
                        <Text className="text-xs text-gray-700 text-center mt-1">
                          {top3Winners[1].wins} {top3Winners[1].wins > 1 ? 'victoires' : 'victoire'}
                        </Text>
                      </View>
                    </View>
                  )}

                  {/* 1ère place */}
                  {top3Winners[0] && (
                    <View className="flex-1 items-center mx-1">
                      <Ionicons name="trophy" size={32} color="#FDB022" className="mb-2" />
                      <View
                        className={`w-20 h-20 rounded-full items-center justify-center mb-2 border-4 border-yellow-400 ${
                          getMemberAvatarColor(top3Winners[0].member.id).bg
                        }`}
                      >
                        <Text
                          className={`text-2xl font-bold ${
                            getMemberAvatarColor(top3Winners[0].member.id).text
                          }`}
                        >
                          {top3Winners[0].member.username.charAt(0).toUpperCase()}
                        </Text>
                      </View>
                      <View className="bg-yellow-400 w-full rounded-t-lg p-3" style={{ height: 120 }}>
                        <Text className="text-sm font-bold text-yellow-900 text-center">
                          🏆 1er 🏆
                        </Text>
                        <Text
                          className="text-lg font-bold text-yellow-900 text-center"
                          numberOfLines={1}
                        >
                          {top3Winners[0].member.username}
                        </Text>
                        <Text className="text-xs text-yellow-800 text-center mt-1">
                          {top3Winners[0].wins} {top3Winners[0].wins > 1 ? 'victoires' : 'victoire'}
                        </Text>
                      </View>
                    </View>
                  )}

                  {/* 3ème place */}
                  {top3Winners[2] && (
                    <View className="flex-1 items-center mx-1">
                      <Text className="text-3xl mb-2">🥉</Text>
                      <View
                        className={`w-14 h-14 rounded-full items-center justify-center mb-2 ${
                          getMemberAvatarColor(top3Winners[2].member.id).bg
                        }`}
                      >
                        <Text
                          className={`text-lg font-bold ${
                            getMemberAvatarColor(top3Winners[2].member.id).text
                          }`}
                        >
                          {top3Winners[2].member.username.charAt(0).toUpperCase()}
                        </Text>
                      </View>
                      <View className="bg-amber-400 w-full rounded-t-lg p-2" style={{ height: 80 }}>
                        <Text className="text-xs font-bold text-amber-900 text-center">3ème</Text>
                        <Text
                          className="text-sm font-bold text-amber-900 text-center"
                          numberOfLines={1}
                        >
                          {top3Winners[2].member.username}
                        </Text>
                        <Text className="text-xs text-amber-800 text-center mt-1">
                          {top3Winners[2].wins} {top3Winners[2].wins > 1 ? 'victoires' : 'victoire'}
                        </Text>
                      </View>
                    </View>
                  )}
                </View>
              </View>
            ) : (
              <View className="flex-1 items-center justify-center py-12">
                <Ionicons name="trophy-outline" size={64} color="#9CA3AF" />
                <Text className="text-gray-500 mt-4">Aucun gagnant pour le moment</Text>
                <Text className="text-gray-400 text-sm mt-2 text-center">
                  Jouez des parties pour voir le podium !
                </Text>
              </View>
            )}
          </View>
        )}
      </ScrollView>
    </View>
  );
}

// @front/app/pages/game/[id].vue
<template>
  <UContainer>
    <div class="py-6">
      <!-- Bouton retour -->
      <div class="mb-6">
        <UButton
          color="neutral"
          variant="ghost"
          icon="i-lucide-arrow-left"
          size="sm"
          @click="navigateTo('/')"
        >
          Retour à la collection
        </UButton>
      </div>

      <!-- Loading -->
      <div
        v-if="loading"
        class="flex justify-center items-center py-12"
      >
        <UIcon
          name="i-lucide-loader-2"
          class="w-8 h-8 animate-spin text-primary-500"
        />
      </div>

      <!-- Error -->
      <div
        v-else-if="error"
        class="flex flex-col items-center justify-center py-12"
      >
        <p class="text-red-500 mb-4">
          {{ error }}
        </p>
        <UButton
          color="primary"
          @click="navigateTo('/')"
        >
          Retour à la collection
        </UButton>
      </div>

      <!-- Jeu non trouvé -->
      <div
        v-else-if="!jeu"
        class="flex flex-col items-center justify-center py-12"
      >
        <UIcon
          name="i-lucide-alert-circle"
          class="w-16 h-16 text-gray-400 mb-4"
        />
        <h2 class="text-2xl font-bold mb-2">
          Jeu non trouvé
        </h2>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
          Le jeu que vous recherchez n'existe pas ou n'est plus disponible.
        </p>
        <UButton
          color="primary"
          @click="navigateTo('/')"
        >
          Retour à la collection
        </UButton>
      </div>

      <!-- Détails du jeu -->
      <div
        v-else
        class="space-y-6"
      >
        <!-- Card avec image et infos synthétiques -->
        <UCard>
          <template #header>
            <div class="flex items-start justify-between gap-2">
              <h1 class="text-xl font-bold wrap-break-word min-w-0 flex-1">
                {{ jeu.titre }}
              </h1>
              <div class="flex items-center gap-2 shrink-0">
                <UButton
                  color="neutral"
                  variant="ghost"
                  icon="i-lucide-edit"
                  size="sm"
                  @click="openEditModal"
                />
              </div>
            </div>
          </template>

          <div class="flex flex-col gap-4">
            <div class="w-full h-48 rounded-lg bg-gray-100 dark:bg-gray-800 flex items-center justify-center overflow-hidden">
              <img
                v-if="jeu && jeu.image"
                :src="jeu.image"
                :alt="jeu.titre || 'Image du jeu'"
                class="w-full h-full object-contain"
              >
              <div
                v-else
                class="flex flex-col items-center justify-center text-gray-400 dark:text-gray-500 p-4"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="w-16 h-16 mb-2"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="1.5"
                    d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"
                  />
                </svg>
                <span class="text-xs text-center">Aucune image</span>
              </div>
            </div>
            <div
              v-if="averageRating > 0"
              class="flex items-center gap-2 p-2 bg-primary-50 dark:bg-primary-900/20 rounded-lg"
            >
              <StarRating
                :model-value="averageRating"
                size="sm"
                readonly
              />
            </div>
            <!-- Podium des top 3 -->
            <div
              v-if="top3Winners.length > 0"
              class="p-4 bg-gradient-to-br from-yellow-50 to-amber-50 dark:from-yellow-900/20 dark:to-amber-900/20 rounded-lg"
            >
              <h3 class="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-4 text-center">
                Podium
              </h3>
              <div class="flex items-end justify-center gap-2">
                <!-- 2ème place -->
                <div
                  v-if="top3Winners[1]"
                  class="flex flex-col items-center flex-1 max-w-[120px]"
                >
                  <div :class="['w-16 h-16 rounded-full flex items-center justify-center mb-2', getMemberAvatarColor(top3Winners[1].member.id).bg]">
                    <span :class="['text-lg font-bold', getMemberAvatarColor(top3Winners[1].member.id).text]">
                      {{ top3Winners[1].member.username.charAt(0).toUpperCase() }}
                    </span>
                  </div>
                  <div
                    class="w-full bg-gray-300 dark:bg-gray-600 rounded-t-lg p-3 text-center"
                    style="height: 80px;"
                  >
                    <div class="flex flex-col items-center justify-center h-full">
                      <span class="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-1">2ème</span>
                      <span class="text-xs font-bold text-gray-900 dark:text-gray-100 truncate w-full">
                        {{ top3Winners[1].member.username }}
                      </span>
                      <span class="text-xs text-gray-600 dark:text-gray-400 mt-1">
                        {{ top3Winners[1].wins }} {{ top3Winners[1].wins > 1 ? 'victoires' : 'victoire' }}
                      </span>
                    </div>
                  </div>
                </div>

                <!-- 1ère place -->
                <div
                  v-if="top3Winners[0]"
                  class="flex flex-col items-center flex-1 max-w-[120px]"
                >
                  <div class="mb-2">
                    <UIcon
                      name="i-lucide-crown"
                      class="w-6 h-6 text-yellow-500"
                    />
                  </div>
                  <div :class="['w-20 h-20 rounded-full flex items-center justify-center mb-2 border-4 border-yellow-400', getMemberAvatarColor(top3Winners[0].member.id).bg]">
                    <span :class="['text-xl font-bold', getMemberAvatarColor(top3Winners[0].member.id).text]">
                      {{ top3Winners[0].member.username.charAt(0).toUpperCase() }}
                    </span>
                  </div>
                  <div
                    class="w-full bg-yellow-400 dark:bg-yellow-600 rounded-t-lg p-3 text-center"
                    style="height: 100px;"
                  >
                    <div class="flex flex-col items-center justify-center h-full">
                      <span class="text-xs font-semibold text-yellow-900 dark:text-yellow-100 mb-1">1er</span>
                      <span class="text-sm font-bold text-yellow-900 dark:text-yellow-100 truncate w-full">
                        {{ top3Winners[0].member.username }}
                      </span>
                      <span class="text-xs text-yellow-800 dark:text-yellow-200 mt-1">
                        {{ top3Winners[0].wins }} {{ top3Winners[0].wins > 1 ? 'victoires' : 'victoire' }}
                      </span>
                    </div>
                  </div>
                </div>

                <!-- 3ème place -->
                <div
                  v-if="top3Winners[2]"
                  class="flex flex-col items-center flex-1 max-w-[120px]"
                >
                  <div :class="['w-16 h-16 rounded-full flex items-center justify-center mb-2', getMemberAvatarColor(top3Winners[2].member.id).bg]">
                    <span :class="['text-lg font-bold', getMemberAvatarColor(top3Winners[2].member.id).text]">
                      {{ top3Winners[2].member.username.charAt(0).toUpperCase() }}
                    </span>
                  </div>
                  <div
                    class="w-full bg-amber-300 dark:bg-amber-700 rounded-t-lg p-3 text-center"
                    style="height: 60px;"
                  >
                    <div class="flex flex-col items-center justify-center h-full">
                      <span class="text-xs font-semibold text-amber-900 dark:text-amber-100 mb-1">3ème</span>
                      <span class="text-xs font-bold text-amber-900 dark:text-amber-100 truncate w-full">
                        {{ top3Winners[2].member.username }}
                      </span>
                      <span class="text-xs text-amber-800 dark:text-amber-200 mt-1">
                        {{ top3Winners[2].wins }} {{ top3Winners[2].wins > 1 ? 'victoires' : 'victoire' }}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="flex flex-wrap gap-2">
              <UBadge
                color="neutral"
                variant="subtle"
                class="whitespace-nowrap"
              >
                {{ jeu.age_min }}{{ jeu.age_max ? `-${jeu.age_max}` : '+' }} ans
              </UBadge>
              <UBadge
                v-for="tag in jeu.tags"
                :key="tag"
                :color="tag.includes('joueurs') ? 'info' : 'primary'"
                variant="subtle"
              >
                {{ tag }}
              </UBadge>
            </div>
          </div>
        </UCard>

        <!-- Onglets -->
        <UTabs
          :items="tabs"
          class="w-full"
        >
          <template #notes>
            <div class="space-y-6 py-6">
              <div
                v-if="familyMembers.length > 0"
              >
                <div class="space-y-4">
                  <div
                    v-for="member in familyMembers"
                    :key="member.id"
                    class="p-4 bg-gray-50 dark:bg-gray-800 rounded-lg"
                  >
                    <div class="flex items-center gap-3 mb-3">
                      <div :class="['w-10 h-10 rounded-full flex items-center justify-center', getMemberAvatarColor(member.id).bg]">
                        <span :class="['text-sm font-semibold', getMemberAvatarColor(member.id).text]">
                          {{ member.username?.charAt(0).toUpperCase() }}
                        </span>
                      </div>
                      <div class="flex items-center justify-between flex-1">
                        <span class="font-medium">{{ member.username }}</span>
                        <UButton
                          v-if="getMemberRating(member.id) > 0"
                          color="red"
                          variant="ghost"
                          icon="i-lucide-trash-2"
                          size="xs"
                          @click="setMemberRating(member.id, 0)"
                        />
                      </div>
                    </div>
                    <div class="flex justify-center">
                      <StarRating
                        :model-value="getMemberRating(member.id)"
                        size="lg"
                        @update:model-value="(rating) => setMemberRating(member.id, rating)"
                      />
                    </div>
                  </div>
                </div>

                <!-- Note moyenne -->
                <div
                  v-if="averageRating > 0"
                  class="mt-4 p-4 bg-primary-50 dark:bg-primary-900/20 rounded-lg"
                >
                  <div class="flex items-center justify-between">
                    <span class="font-semibold text-primary-900 dark:text-primary-100">
                      Note moyenne
                    </span>
                    <div class="flex items-center gap-2">
                      <StarRating
                        :model-value="averageRating"
                        readonly
                      />
                      <span class="text-lg font-bold text-primary-600 dark:text-primary-400">
                        {{ averageRating.toFixed(1) }} / 5
                      </span>
                    </div>
                  </div>
                </div>
              </div>
              <div
                v-else
                class="text-center py-12 text-gray-500 dark:text-gray-400"
              >
                <UIcon
                  name="i-lucide-users"
                  class="w-16 h-16 mx-auto mb-4 opacity-50"
                />
                <p>Aucun membre dans la famille</p>
              </div>
            </div>
          </template>

          <template #parties>
            <GameSessions
              v-if="gameId"
              :game-id="gameId"
            />
          </template>
        </UTabs>
      </div>
    </div>

    <!-- Modal de modification -->
    <AddGameModal
      v-model="isModalOpen"
      :game="jeu"
      @success="handleGameUpdated"
    />
  </UContainer>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useFamilyStore, type Rating } from '~/stores/family'
import StarRating from '~/components/StarRating.vue'
import GameSessions from '~/components/GameSessions.vue'

definePageMeta({
  layout: 'default',
  middleware: 'auth'
})

const route = useRoute()
const familyStore = useFamilyStore()

const isModalOpen = ref(false)
const loading = ref(true)
const error = ref<string | null>(null)
const top3Winners = ref<Array<{ member: { id: number, username: string }, wins: number }>>([])

// Définir les onglets avec des slots personnalisés
const tabs = [
  {
    label: 'Notes',
    icon: 'i-lucide-star',
    slot: 'notes'
  },
  {
    label: 'Parties',
    icon: 'i-lucide-gamepad-2',
    slot: 'parties'
  }
]

// Récupérer l'ID depuis la route
const gameId = computed(() => {
  const id = route.params.id
  return typeof id === 'string' ? parseInt(id, 10) : null
})

// Trouver le jeu dans le store
const jeu = computed(() => {
  if (!gameId.value) return null
  return familyStore.transformedGames.find(g => g.id === gameId.value)
})

// Récupérer les membres de la famille
const familyMembers = computed(() => familyStore.familyMembers)

// Charger les top 3 gagnants
const loadTop3Winners = async () => {
  if (!gameId.value) return

  const result = await familyStore.getTop3Winners(gameId.value)
  if (result.success && result.data) {
    top3Winners.value = result.data
  } else {
    top3Winners.value = []
  }
}

// Charger la famille au montage
onMounted(async () => {
  try {
    loading.value = true
    await familyStore.fetchFamily()

    if (!jeu.value) {
      error.value = 'Jeu non trouvé'
    } else {
      await loadTop3Winners()
    }
  } catch (err) {
    console.error('Erreur lors du chargement du jeu:', err)
    error.value = 'Erreur lors du chargement du jeu'
  } finally {
    loading.value = false
  }
})

// Recharger les top 3 gagnants quand le jeu change
watch(gameId, () => {
  if (gameId.value) {
    loadTop3Winners()
  }
})

// Ouvrir le modal de modification
const openEditModal = () => {
  isModalOpen.value = true
}

// Gérer la mise à jour du jeu
const handleGameUpdated = async () => {
  await familyStore.fetchFamily()
  await loadTop3Winners()
  isModalOpen.value = false
}

// Récupérer la note d'un membre
const getMemberRating = (memberId: number): number => {
  if (!jeu.value?.ratings) return 0
  const memberRating = jeu.value.ratings.find((r: Rating) => r.member.id === memberId)
  return memberRating ? memberRating.rating : 0
}

// Définir la note d'un membre
const setMemberRating = async (memberId: number, rating: number) => {
  if (!gameId.value) return

  try {
    const result = await familyStore.setRating(gameId.value, memberId, rating)

    if (!result.success) {
      console.error('Erreur lors de l\'enregistrement de la note:', result.error)
      error.value = result.error || 'Erreur lors de l\'enregistrement de la note'
    }
  } catch (err) {
    console.error('Erreur lors de l\'enregistrement de la note:', err)
    error.value = 'Erreur lors de l\'enregistrement de la note'
  }
}

// Calculer la note moyenne
const averageRating = computed(() => {
  if (!jeu.value?.ratings || jeu.value.ratings.length === 0) return 0

  const ratings = jeu.value.ratings.filter((r: Rating) => r.rating > 0)
  if (ratings.length === 0) return 0

  const sum = ratings.reduce((acc: number, r: Rating) => acc + r.rating, 0)
  return sum / ratings.length
})

// Obtenir les classes de couleur pour l'avatar d'un membre
const getMemberAvatarColor = (memberId: number) => {
  const colors = [
    { bg: 'bg-primary-100 dark:bg-primary-900', text: 'text-primary-600 dark:text-primary-400' },
    { bg: 'bg-info-100 dark:bg-info-900', text: 'text-info-600 dark:text-info-400' },
    { bg: 'bg-success-100 dark:bg-success-900', text: 'text-success-600 dark:text-success-400' },
    { bg: 'bg-warning-100 dark:bg-warning-900', text: 'text-warning-600 dark:text-warning-400' },
    { bg: 'bg-red-100 dark:bg-red-900', text: 'text-red-600 dark:text-red-400' },
    { bg: 'bg-purple-100 dark:bg-purple-900', text: 'text-purple-600 dark:text-purple-400' },
    { bg: 'bg-pink-100 dark:bg-pink-900', text: 'text-pink-600 dark:text-pink-400' },
    { bg: 'bg-indigo-100 dark:bg-indigo-900', text: 'text-indigo-600 dark:text-indigo-400' }
  ]
  const colorIndex = memberId % colors.length
  return colors[colorIndex]
}
</script>
